function excludeTags (tags) {
  const toExclude = [
    'adult',
    'adult-game',
    'blowjob',
    'bondage',
    'boobs',
    'controversial',
    'crush',
    'date',
    'dating',
    'dating-sim',
    'dating-simulator',
    'ecchi',
    'eroge',
    'erotic',
    'exe',
    'fat',
    'fellatio',
    'femdom',
    'fetish',
    'futanari',
    'guro',
    'hentai',
    'incest',
    'khentai',
    'lewd',
    'loli',
    'masturbation',
    'milf',
    'nsfw',
    'porn',
    'pussy',
    'rape',
    'ryona',
    'sex',
    'sex-game',
    'sexual',
    'sexual-content',
    'sexy',
    'trump',
    'vore',
    'xxx',
    'yandere'
  ]
  return !tags.some(tag => toExclude.includes(tag.slug))
}

export default excludeTags
